### ISSUE TITLE
The same interactive map in leaflet

### ISSUE THREAD

**Issue by lperozzi** [lao-tseu-is-alive/lausanne-map-wmts-mn95#1]
Hi,

it is possible to use this in Leaflet?

Many thanks

**Comment by lao-tseu-is-alive** [comment]
This repo is an example with OpenLayers
To use the same WMTS server with Leaflet please have look to  
this repo : https://github.com/lao-tseu-is-alive/lausanne-map-wmts-mn95-leaflet

**Comment by lao-tseu-is-alive** [comment]
will add a link in readme to help users go to the right repo depending on the lib they want to use

**Comment by lperozzi** [comment]
Hi @lao-tseu-is-alive,

many thanks for your help! Really appreciated

**Comment by lperozzi** [comment]
Hi @lao-tseu-is-alive,

another question. Is there a way to use  the same WMTS server with mapbox/maplibre?
